FROM devspaces/bazel

LABEL \
    "com.trilogy.company"="External" \
    "com.trilogy.stage"="dev" \
    "com.trilogy.maintainer.skype"="otaviocx" \
    "com.trilogy.maintainer.email"="otaviocalaca.xavier@aurea.com" \
    "description"="This file generates a docker image containing Open JDK 8, Bazel and tools needed to build Bazel project"

WORKDIR /data
