FROM devspaces/bigbluebutton

LABEL \
    "com.trilogy.product"="BigBlueButton" \
    "com.trilogy.company"="External" \
    "com.trilogy.stage"="dev" \
    "com.trilogy.maintainer.skype"="otaviocx" \
    "com.trilogy.maintainer.email"="otaviocalaca.xavier@aurea.com" \
    "description"="This file generates a docker image containing Open JDK 8, Flex and tools needed to build BigBlueButton project"

WORKDIR /data
